# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/relation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProDlg(object):
    def setupUi(self, ProDlg):
        ProDlg.setObjectName("ProDlg")
        ProDlg.resize(400, 156)
        font = QtGui.QFont()
        font.setPointSize(14)
        ProDlg.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(ProDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ProDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(ProDlg)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(ProDlg)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ProDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(ProDlg)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_accept = QtWidgets.QPushButton(ProDlg)
        self.btn_accept.setObjectName("btn_accept")
        self.horizontalLayout.addWidget(self.btn_accept)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_reject = QtWidgets.QPushButton(ProDlg)
        self.btn_reject.setObjectName("btn_reject")
        self.horizontalLayout.addWidget(self.btn_reject)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 1)

        self.retranslateUi(ProDlg)
        self.btn_accept.clicked.connect(ProDlg.accept)
        self.btn_reject.clicked.connect(ProDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ProDlg)

    def retranslateUi(self, ProDlg):
        _translate = QtCore.QCoreApplication.translate
        ProDlg.setWindowTitle(_translate("ProDlg", "Dialog"))
        self.label.setText(_translate("ProDlg", "Table_name :"))
        self.label_2.setText(_translate("ProDlg", "Property_name :"))
        self.label_3.setText(_translate("ProDlg", "Property_type :"))
        self.btn_accept.setText(_translate("ProDlg", "Accept"))
        self.btn_reject.setText(_translate("ProDlg", "Reject"))
