# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ForeignKey.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForDlg(object):
    def setupUi(self, ForDlg):
        ForDlg.setObjectName("ForDlg")
        ForDlg.resize(526, 226)
        font = QtGui.QFont()
        font.setPointSize(14)
        ForDlg.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(ForDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ForDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(ForDlg)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ForDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(ForDlg)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ForDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(ForDlg)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ForDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(ForDlg)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(ForDlg)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(ForDlg)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_accept = QtWidgets.QPushButton(ForDlg)
        self.btn_accept.setObjectName("btn_accept")
        self.horizontalLayout.addWidget(self.btn_accept)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_reject = QtWidgets.QPushButton(ForDlg)
        self.btn_reject.setObjectName("btn_reject")
        self.horizontalLayout.addWidget(self.btn_reject)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 2)

        self.retranslateUi(ForDlg)
        self.btn_accept.clicked.connect(ForDlg.accept)
        self.btn_reject.clicked.connect(ForDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ForDlg)

    def retranslateUi(self, ForDlg):
        _translate = QtCore.QCoreApplication.translate
        ForDlg.setWindowTitle(_translate("ForDlg", "Dialog"))
        self.label.setText(_translate("ForDlg", "Foreign_Key_Name :"))
        self.label_2.setText(_translate("ForDlg", "Source_Table :"))
        self.label_3.setText(_translate("ForDlg", "Source_Property :"))
        self.label_4.setText(_translate("ForDlg", "Target_Table :"))
        self.label_5.setText(_translate("ForDlg", "Target_Property :"))
        self.btn_accept.setText(_translate("ForDlg", "Accept"))
        self.btn_reject.setText(_translate("ForDlg", "Reject"))
